### ISSUE TITLE
"Query" button grayed out

### ISSUE THREAD

**Issue by triska** [guregu/trealla-js#10]
When I now visit https://php.energy/trealla.html using Firefox 78.15.0esr (64-bit), Chrome or Safari on OSX, the "Query" button is unexpectedly grayed out, and I cannot post a query (also not using ENTER).

This is highly unexpected, what could be the reason for this?

**Comment by guregu** [comment]
Sorry about that. It starts grayed out until the library loads and initializes as a very crude loading bar. Need to add an error message when it fails. Might be related to #11. Will take a look. If you look at the browsers develop console output it should tell you why it failed.

**Comment by triska** [comment]
When loading the page in Firefox, the single message I see in the console is:

<pre>
[Exception... "Favicon at "https://php.energy/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 227"  data: no] [FaviconLoader.jsm:227:22](resource:///modules/FaviconLoader.jsm)
    onStopRequest resource:///modules/FaviconLoader.jsm:227
</pre>

So, it seems that the only issue is that `favicon.ico` failed to load, this seems not so serious.

**Comment by triska** [comment]
Thank you, this works as expected now on OSX!
