### ISSUE TITLE
Sandbox should somehow indicate whether or not "?- " must be entered

### ISSUE THREAD

**Issue by triska** [guregu/trealla-js#12]
Logically, a goal clause is a Horn clause with empty head, i.e., of the form:

<pre>
&emptyset; &leftarrow; Goal.
</pre>

Syntactically, if we only see:

<pre>
Goal.
</pre>

then that could indicate a Horn clause with an empty *body*, which would be a *fact* instead of a query:

<pre>
Goal &leftarrow; &emptyset;
</pre>

Currently, the sandox https://php.energy/trealla.html expects users to enter a goal as a query, but syntactically the goal alone could be interpreted as a fact, because it is not made clear whether the head or the body is empty. Personally, when I see a completely blank input field and want to post a query, I would start by writing `?- `, and then write the goal. However, that's not what the sandox expects: The sandbox expects me to *not* write `?- `, but only the goal. Currently, there is no indication whether or not `?- ` must be entered.

There are several ways to solve this. One elegant way to do this would be to include the hardcoded (and unmodifiable) string `?- ` *as part of the string in the textbox* which is written in front of the query that the user posts.

This would correspond to the way Prolog toplevels work on the terminal: The system emits `?- ` for us, *so that we do not have to enter it*. Logically, this `?- ` *is regarded as part of the user input*.

**Comment by guregu** [comment]
That makes sense, thanks. I updated it to include a `?- ` in front of the text box. I would like to change the design so that it looks like it is more of a part of the prompt. Maybe along with #9.

**Comment by triska** [comment]
Thank you a lot!
