### ISSUE TITLE
Residual constraints missing

### ISSUE THREAD

**Issue by triska** [guregu/trealla-js#4]
Currently, when I post `?- dif(X, Y).`, then I get:

<pre>
{
  "result": "success",
  "answer": {
    "X": {
      "var": "_"
    },
    "Y": {
      "var": "_"
    }
  },
  "output": ""
}
</pre>

This is too general: The expected answer is a residual goal that is equivalent to `dif(X, Y)`.

For comparison, with Trealla:

<pre>
<b>$ ./tpl 
?- dif(X, Y).</b>
   dif:dif(X,Y), dif:dif(X,Y).
</pre>

**Comment by guregu** [comment]
Thanks for bringing that up. I think I should be able to get the variable name and residual goals in there.

**Comment by guregu** [comment]
Something like this maybe? (Also has atoms changed to look the same as compounds)

```json
{
  "result": "success",
  "answer": {
    "X": {
      "var": "X",
      "attr": [
        {
          "functor": ":",
          "args": [
            {
              "functor": "dif"
            },
            {
              "functor": "dif",
              "args": [
                {
                  "var": "X"
                },
                {
                  "var": "Y"
                }
              ]
            }
          ]
        }
      ]
    },
    "Y": {
      "var": "Y",
      "attr": [
        {
          "functor": ":",
          "args": [
            {
              "functor": "dif"
            },
            {
              "functor": "dif",
              "args": [
                {
                  "var": "X"
                },
                {
                  "var": "Y"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

#6 is also an interesting consideration, hmm... 🤔

**Comment by triska** [comment]
Conceptually, all types of answers can be uniformly represented as a sequence of Prolog *goals*. If the answer is an answer substitution, we get a conjunction of `Var = Term` goals. If there are residual constraints, we get them as goals, possibly *in conjunction* with answer substitutions. If an exception arose, that's again a goal such as `throw(...)` or `error(...,...)`.

You can use `copy_term/3` to project any remaining attributes into residual constraints, for example:

<pre>
<b>?- dif(X, Y), copy_term(X-Y, X-Y, Goals).</b>
   Goals = [dif:dif(X,Y),dif:dif(X,Y)].
</pre>

**Comment by triska** [comment]
One additional point: It may help to roll your own custom toplevel in Prolog, and use that as a flexible interface that could also be dynamically changed or extended if users need a different format. A simple Prolog toplevel can be implemented with a few primitives:

1. read a query with read_term/2, using the **`variable_names/2`** option to get the names of variables that occur in the query.
2. use `call/1` to execute the query.
3. use `copy_term/3` project remaining attributes into residual goals
4. emit the answer, using the `variable_names/2` option for *writing* the term.

**Comment by guregu** [comment]
@triska Here is the current code for the toplevel:
https://github.com/guregu/trealla/blob/main/library/js_toplevel.pl
It's living in my fork right now but I would like to upstream it when possible.
There is some weirdness in it to work around some limitations of WASM runtimes.
Let me know if it can be improved, I imagine I am missing some stuff.

I updated it to return residual goals for each variable as in https://github.com/guregu/trealla-js/issues/4#issuecomment-1261480298. Currently the API returns a mapping of variables to substitutions. I realize this isn't as conceptually pure as the regular toplevel but it's meant to be more low-level (i.e. you could use it to build a proper toplevel). I am trying to strike a balance between ease of use and conceptual purity.
I do like the idea of pluggable toplevels though, it shouldn't be too hard to get it to return the same output as `tpl` as Prolog text instead of JS objects.

Please feel free to nitpick the naming of the fields and the shape of the API and stuff, I trust your judgment 🙂

**Comment by triska** [comment]
In this snippet, I noticed two things: `copy_term/3` should be used with the first argument *identical* to the second argument, otherwise the variables in the residual goals are fresh copies and not identical to the intended variables of the term. Therefore, use for example `copy_term(V, V, Gs)` to obtain the residual constraints `Gs` that `V` is involved in. If you use `copy_term(X, _, Gs)`, then the variables in `Gs` are fresh copies.

Second, a DCG could be more suitable to describe, as a list of characters, the JSON output that corresponds to a term. In particular, check out the nonterminal `format_//2` from `library(format)` which you can use in DCGs, and which lets you eliminate `atom_chars/2` and other predicates in a uniform manner. For example:

<pre>
json(Term) --> { atom(Term) }, !, format_("~q", [Term]).
...
</pre>

You can use `phrase(json(Term), Cs)` to obtain the list `Cs`. The advantage of this is that you can more easily test the toplevel via Prolog queries. For actual output, you can use `format/2` as a single small additional step, which is the only part in the program where side-effects occur (and which therefore cannot be readily tested from within Prolog).

**Comment by guregu** [comment]
Thanks! I have fixed the `copy_term/3` usage.
I agree a DCG would be nicer. I'll look into refactoring it to use `format_//2`.

In the meantime I have provided a way to get Trealla's actual toplevel output as text (#7).
I updated the demo site to use it.

https://php.energy/trealla.html?src=&q=dif%28X%2C+Y%29%3B+dif%28A%2C+B%29.&v=0

```
?- dif(X, Y); dif(A, B).
   dif:dif(X,Y)
;  dif:dif(A,B).
```

**Comment by guregu** [comment]
Closing now that we have the regular Trealla toplevel available in the "prolog" format. The JSON format makes a best effort attempt to report residual goals. I'd like to take a closer look at the JSON format especially when Trealla officially supports clp(z). Feel free to re-open anytime.
