### ISSUE TITLE
Atoms look like strings in answers

### ISSUE THREAD

**Issue by triska** [guregu/trealla-js#5]
Currently, when I post `X = "abc"`, I get, **as expected**:

<pre>
{
  "result": "success",
  "answer": {
<b>    "X": "abc"</b>
  },
  "output": ""
}
</pre>

However, when I post `X = abc`, I also get:

<pre>

{
  "result": "success",
  "answer": {
<b>    "X": "abc"</b>
  },
  "output": ""
}
</pre>

even though `"abc"` and `abc` are not the same term.

**Comment by guregu** [comment]
I updated the types to disambiguate them.

```prolog
?- X = foo, Y = "bar".
```

```json
{
  "result": "success",
  "answer": {
    "X": {
      "functor": "foo"
    },
    "Y": "bar"
  },
  "output": ""
}
```

New types:
```typescript
/*
	Default encoding (in order of priority):
	string(X) 	→ string
	is_list(X)	→ List
	atom(X) 	→ Atom
	compound(X)     → Compound
	number(X) 	→ number
	var(X) 		→ Variable
*/
type Term = Atom | Compound | Variable | List | string | number;

interface Atom {
	functor: string;
}

interface Compound {
	functor: string;
	args: Term[];
}

interface Variable {
	var: string;   // variable name
	attr?: Term[]; // residual goals
}

type List = Term[];
```

**Comment by guregu** [comment]
Also added an option parameter to the query methods to change how encoding works for strings and atoms, for those who want to tweak it.

```js
// to get the previous behavior:
pl.query(`X = foo.`, {encode: {atoms: "string"}};
```

**Comment by guregu** [comment]
Closing as I think it's done, but please feel free to reopen this or any other issue in the future. I appreciate the help.
