### ISSUE TITLE
Errors can be reported as residual goals

### ISSUE THREAD

**Issue by triska** [guregu/trealla-js#6]
For example, in Scryer Prolog, we get:

<pre>
<b>?- throw(t).</b>
   throw(t).
<b>?- T =.. a.</b>
   error(type_error(list,a),(=..)/2).
<b>?- X =:= Y.</b>
   error(instantiation_error,(is)/2).
</pre>

Note that exceptions are reported "uniformly" as **residual goals**, much like constraints and answer substitutions, using the predicates `error/2` and `throw/1`.

This may be worth considering in the API design. It is related to #4.

**Comment by guregu** [comment]
I'm not sure if we can express this in a nice way with the variable substitution format the response currently uses 🤔 

IIRC, the way Tau does this is it reports either a map of substitutions or a goal corresponding to the thrown ball, but this leads to kind of an ugly API situation where the response shape can be totally different, so you have to use a helper function (`pl.types.is_error` in Tau). Being able to switch on the response status is a little bit nicer.

**Comment by guregu** [comment]
I never thought about errors being conceptually the same as residual goals though, that's actually kind of mind blowing, haha.

**Comment by guregu** [comment]
In the latest release you can use the Prolog format to get this.

```
% demo toplevel looks like this now
?- throw(t).
   throw(t).
?- T =.. a.
   error(type_error(list,a),(=..)/2).
?- X =:= Y.
   error(instantiation_error,number).
```

```javascript
const goal = await pl.queryOnce("throw(t).", {format: "prolog"});
// goal = "throw(t)."
```

**Comment by guregu** [comment]
Closing as done because the Prolog format toplevel report answers the same as regular Trealla now. I would like to further improve the uniformity by splitting the variable dump: #20.
